library("corrplot")
head(mtcars)
corr <- cor(mtcars)
corrplot(corr)
corrplot(corr, method = "number", type = "upper", title = "")
corrplot(corr, method = "pie", type = "lower", title = "下三角",mar = c(1,1,1,1))
corrplot(corr, method = "ellipse", col = colorRampPalette(c("red", "blue"))(10), title = "更改颜色")
corrplot(corr, method = "number", col = RColorBrewer::brewer.pal(n=11, name = "RdYlGn"),title = "")
corrplot(corr,method="color",order="hclust",title = "hclust聚类", diag = TRUE,hclust.method="average",addCoef.col = "blue")
corrplot(corr, method = "circle", type = "upper", tl.pos = "d")
corrplot(corr, add = TRUE, type = "lower", method = "number", diag = FALSE, tl.pos = "n", cl.pos = "n")


mtcars_test=read.table("NEB_abundance.txt",header = T)
corr_test=cor(mtcars_test)
corrplot(corr_test)
#corrplot(corr_test,method = "number",type = "upper",title = "")
#corrplot(corr_test, method = "pie", type = "lower", title = "",mar = c(1,1,1,1))
corrplot(corr_test, title = 'NEB', mar=c(0, 0, 1, 0), tl.pos = 'p')
#corrplot(corr_test, method = "ellipse", mar=c(0, 0, 1, 0),col = colorRampPalette(c("red", "blue"))(10), title = "illumina")
#corrplot(corr_test, method = "number", col = RColorBrewer::brewer.pal(n=11, name = "RdYlGn"),title = "")
#corrplot(corr_test,method="color",order="hclust",title = "hclust聚类", diag = TRUE,hclust.method="average",addCoef.col = "blue")
corrplot(corr_test, method = "circle", type = "upper", tl.pos = "d")
#corrplot(corr_test, add = TRUE, type = "lower", method = "number", diag = FALSE, tl.pos = "n", cl.pos = "n")
